site_name: tools/bblocks/datacommons-tools

nav:
    - index.md
    - Why bblocks-datacommons-tools: why-bblocks-datacommons-tools.md
    - Getting started: getting-started.md
    - Using the Explicit Schema: explicit-schema.md
    - Using the Implicit Schema: implicit-schema.md
    - Loading Data to the Knowledge Graph: loading-data.md
    - Other tools: other-tools.md
    - Changelog: changelog.md