site_name: tools/bblocks/datacommons-tools

nav:
    - index.md
    - Getting started: getting-started.md
    - Preparing data: preparing-data.md
    - Data Commons schemas: dc-schemas.md
    - Loading data: loading-data.md
    - CLI tools: cli-tools.md
    - Changelog: changelog.md